#!/bin/bash

# DEFINE DIRECTORIES
RESULTSDIR="/data/results/"
DOCKER="DOCKER_"
WEBSERVER="WEBSERVER_"
FILESERVER="FILESERVER_"
VARMAIL="VARMAIL_"
OLTP="OLTP_"
WEBPROXY="WEBPROXY_"
VIDEOSERVER="VIDEOSERVER_"
CLEAN="CLEAN_"
EXT=".txt"
XYZ=`df -TH | grep "^/dev"`
FS=`./src/determineFS.sh $XYZ`


for i in `seq 1 5`
do
	#18 header lines for webserver
	#1 tail line for webserver
	#tail $RESULTSDIR$FS$WEBSERVER$i$EXT

	tail -n +19 $RESULTSDIR$DOCKER$FS$WEBSERVER$i$EXT | head -n -1 > $RESULTSDIR$DOCKER$CLEAN$FS$WEBSERVER$i$EXT

	tail -n +15 $RESULTSDIR$DOCKER$FS$FILESERVER$i$EXT | head -n -1 > $RESULTSDIR$DOCKER$CLEAN$FS$FILESERVER$i$EXT

	tail -n +15 $RESULTSDIR$DOCKER$FS$VARMAIL$i$EXT | head -n -1 > $RESULTSDIR$DOCKER$CLEAN$FS$VARMAIL$i$EXT

	tail -n +15 $RESULTSDIR$DOCKER$FS$WEBPROXY$i$EXT | head -n -1 > $RESULTSDIR$DOCKER$CLEAN$FS$WEBPROXY$i$EXT

	tail -n +20 $RESULTSDIR$DOCKER$FS$VIDEOSERVER$i$EXT | head -n -1 > $RESULTSDIR$DOCKER$CLEAN$FS$VIDEOSERVER$i$EXT
	

done